### ISSUE TITLE
Errors compiling under OSX

### ISSUE THREAD

**Issue by sabotage3d** [gawag/Urho-Sample-Platformer#6]
Hi I am trying to compile your game sample under OSX but I am getting some errors.
I have enabled C++11 using `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1462:36: No matching constructor for initialization of 'std::__1::unique_ptr<game_state, std::__1::default_delete<game_state> >'`

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2424:27: Invalid application of 'sizeof' to an incomplete type 'player'`

`/Users/sabotage3d/DEV/Urho-Sample-Platformer/Source/main.cpp:121:42: No member named 'emplace_back' in 'std::__1::vector<std::__1::unique_ptr<game_state, std::__1::default_delete<game_state> >, std::__1::allocator<std::__1::unique_ptr<game_state, std::__1::default_delete<game_state> > > >'`

**Comment by sabotage3d** [comment]
Solved with:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")`

**Comment by damu** [comment]
Hi,
Oh yeah I know that issue from my job. That's because the default STL used on Mac OS X (libstdc++? usually used by GCC) is so outdated that it doesn't properly support C++11. It needs to be switched to libc++ (usually used by clang) with "-stdlib=libc++".
I'll add that tomorrow to a build instruction site and also update the Urho build tutorial in the wiki with the non CMake-GUI variant of activating C++11 and switching the STL for Mac OS X.

Where did you find USP? In the Urho wiki which I was still extending? (it's mostly done now) I thought the wiki had like no visitors because it wasn't that active for a while. I'm still like the only one doing something on it. (I plan on advertising it a bit by writing about USP on the Urho forum, maybe it'll get more active again).

**Comment by sabotage3d** [comment]
Hey man,
Everything works now. I found your wiki on google where was the USP sample link. It is very cool example if you make a breakdown of the sample I would be awesome. It is a lot more useful than the Ninja example as it is more self contained.

**Comment by damu** [comment]
The current Urho wiki is at http://urho3d.wikia.com/wiki/Unofficial_Urho3D_Wiki and got more topics recently about stuff that I found out during the development of USP. The wiki was (accidentally) started by me, see http://urho3d.prophpbb.com/topic778.html for the whole story. Urho had a wiki long time ago but that one was closed because of inactivity.
The features of USP are listed here http://urho3d.wikia.com/wiki/USP_-_Urho_Sample_Platformer with links to wiki articles describing details.
There is also a USP wiki with more game related stuff (like possible tricks, ideas, ...) here: https://github.com/gawag/Urho-Sample-Platformer/wiki
Write me if you find something badly written, missing, improvable or add/improve things yourself, help would be welcome ;-). The Wikia Urho Wiki had multiple contributors as it started but that slowed down over time. I'm like the only regular contributor. I try to write about everything new that I make with Urho and also have two new Urho sample projects planned, which will be integrated into the wiki (and earlier as USP did).
There's also my "Urho Blog", the Wikia Message Wall, where I'm writing about stuff I'm currently doing, new stuff in the wiki, upcoming projects, issues with Urho and so on at: http://urho3d.wikia.com/wiki/Message_Wall:Gawag

Oh do you know of some better GUI system which can be used with Urho? That's one of the next things I want to look into as Urho's own UI system is so minimal. I know CeGUI and MyGUI but nothing which has already been combined with Urho.

**Comment by sabotage3d** [comment]
I read all of these man. Pretty interesting stuff. I would advertise it better it would draw more people to urho3d. In this topic: http://urho3d.prophpbb.com/topic838-20.html  I suggested : https://github.com/ocornut/imgui . Another interesting thing is I suggested bgfx as it supports Metal now: http://urho3d.prophpbb.com/topic1067.html and it has natural support for imgui .

**Comment by damu** [comment]
Added build instructions to the readme https://github.com/gawag/Urho-Sample-Platformer/blob/master/Readme.md and added a note for Mac OS X to http://urho3d.wikia.com/wiki/Creating_a_new_Urho3D_Project . This "issues" should be "fixed" now.

Also the last USP feature I wanted to do is done (recording of best times) and commited.
Haven't looked into imgui into such details yet but the thread mentioned it also having issues. Seems like the "better GUI for Urho" is a bigger issue. I hope there is a general good solution which can be advertised and explained in the wiki.
